@ComexAPI_HostAddress = http://localhost:5145

POST {{ComexAPI_HostAddress}}/produto/ 
Content-type: application/json
{
    "Nome":"Pepsi",
    "Descricao": "Uma pepsi cola bem geladinha",
    "Preco": 2.50,
    "Quantidade": 10
}
###
GET http://localhost:5145/produto/ 
Content-type: application/json

###
GET {{ComexAPI_HostAddress}}/produto/2
Content-type: application/json

###
PUT {{ComexAPI_HostAddress}}/produto/2
Content-type: application/json
{
    "Nome":"Coca Colaaaaaaaaa",
    "Descricao": "Uma coca cola bem geladinha",
    "Preco": 3.50,
    "Quantidade": 10
}
###
DELETE {{ComexAPI_HostAddress}}/produto/2
Content-type: application/json

###
POST http://localhost:5145/endereco/ 
Content-type: application/json
{
  "Bairro": "Iraci",
  "Cidade": "Itacoatiara",
  "Complemento": "Não sei",
  "Estado": "AM",
  "Rua": "Joaquimg",
  "Numero": "30"
}

###

GET {{ComexAPI_HostAddress}}/endereco/
Content-type: application/json

###
GET {{ComexAPI_HostAddress}}/endereco/2
Content-type: application/json

###
PUT {{ComexAPI_HostAddress}}/endereco/2
Content-type: application/json
{
  "Bairro": "Colonia",
  "Cidade": "Itacoatiara",
  "Complemento": "Não sei",
  "Estado": "AM",
  "Rua": "Pescaria",
  "Numero": "3033"
}
###
DELETE {{ComexAPI_HostAddress}}/endereco/2
Content-type: application/json


###
POST http://localhost:5145/cliente/ 
Content-type: application/json
{
  "nome": "Henrique",
  "cpf": "4184122401",
  "email": "henrique@email.com",
  "profissao": "dev",
  "telefone": "3520293325",
  "enderecoId": 3
}

###

GET {{ComexAPI_HostAddress}}/cliente/
Content-type: application/json