@ComexAPI_HostAddress = http://localhost:5145

POST {{ComexAPI_HostAddress}}/produto/ 
Content-type: application/json
{
    "Nome":"Pepsi",
    "Descricao": "Uma pepsi cola bem geladinha",
    "Preco": 2.50,
    "Quantidade": 10
}
###
GET {{ComexAPI_HostAddress}}/produto/ 
Content-type: application/json

###
GET {{ComexAPI_HostAddress}}/produto/2
Content-type: application/json

###
PUT {{ComexAPI_HostAddress}}/produto/2
Content-type: application/json
{
    "Nome":"Coca Colaaaaaaaaa",
    "Descricao": "Uma coca cola bem geladinha",
    "Preco": 3.50,
    "Quantidade": 10
}
###
DELETE {{ComexAPI_HostAddress}}/produto/2
Content-type: application/json