openapi: 3.0.3
info:
  title: COMEX-API
  description: Projeto COMEX API, uma api de músicas e bandas.
  termsOfService: http://swagger.io/terms/
  contact:
    email: henrixe80@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Documentação
  url: http://swagger.io
servers:
  - url: http://localhost:3000

paths:
  /produtos:
    get:
      summary: Recupera todos os produtos
      responses: 
        200: 
          description: Sucesso
          content: 
            application/json:
              schema: 
                type: array
                items: 
                  $ref: '#/components/schemas/Produto' 
        404:
          description: Produtos não encontrados
    post:
      summary: Cria novo produto
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/ProdutoIncompleto' 
              
      responses:
        201:
          description: "Sucesso ao criar o produto"
          content: 
            application/json:
              schema: 
                $ref: '#/components/schemas/Produto' 
        400:
          description: "Falha ao criar novo produto"
          
  /produtos/{produtoId}:
    get:
      summary: Recupera produto por Id
      parameters:
      - name: produtoId
        in: path
        description: ID do produto
        required: true
        schema:
          type: integer
            
      responses: 
        200: 
          description: Sucesso
          content: 
            application/json:
              schema: 
                 $ref: '#/components/schemas/Produto' 
        404:
          description: Produtos não encontrados
          
    put:
      summary: Atualiza um produto existente
      parameters:
      - name: produtoId
        in: path
        description: ID do produto
        required: true
        schema:
          type: integer
            
      requestBody:
        content:
          application/json: 
            schema:
              $ref: '#/components/schemas/ProdutoIncompleto' 
              
      responses: 
        204: 
          description: Sem conteudo
        400:
          description: Falha ao atualizar o produto
      
components:
  schemas:
    Produto:
        type: object
        properties:
            Id:
                type: integer
                example: 1
            Nome:
                type: string
                example: "Coca cola"
            Descricao:
                type: string
                example: "Uma coca gelada"
            Preco: 
                type: number
                example : 6.99
            Quantidade: 
                type: integer
                example: 5
            CategoriaId: 
                type: integer
                example: 1
    ProdutoIncompleto:
      type: object
      properties:
          Nome:
            type: string
            example: "Coca cola zero"
          Descricao:
            type: string
            example: "Uma coca geladinha"
          Preco: 
            type: number
            example : 6.99
          Quantidade: 
            type: integer
            example: 5
          CategoriaId: 
            type: integer
            example: 1
              