openapi: 3.0.3
info:
  title: COMEX-API
  description: Projeto COMEX API, uma api de músicas e bandas.
  termsOfService: http://swagger.io/terms/
  contact:
    email: henrixe80@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Documentação
  url: http://swagger.io
servers:
  - url: http://localhost:3000